name: "michaelhost build"
description: "build and push an image update to michaelhost webhook"
author: layerssss

inputs:
  michaelhost_webhook_url:
    description: public URL of michaelhost webhook server
    required: true
  michaelhost_secret:
    description: michaelhost secret
    required: true
  image_name:
    description: image name
    required: true
  image_tag:
    description: image tag
    required: true
    default: latest
  build_context:
    description: path to docker build context
    required: true
    default: .
  build_file:
    description: Dockerfile file name
    required: true
    default: Dockerfile
  registry:
    description: docker registry
    required: true
    default: registry.hub.docker.com
  registry_username:
    description: docker registry username
    required: true
  registry_password:
    description: docker registry password
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
